### ISSUE TITLE
fails to build with x-clipboard 0.9

### ISSUE THREAD

**Issue by daniel-baumann** [dimonomid/nerdlog#56]
Hi,

currently nerdlog fails to build from source when using x-clipboard 0.9:

```
# github.com/dimonomid/nerdlog/clipboard
src/github.com/dimonomid/nerdlog/clipboard/clipboard_supported_platforms.go:33:37: not enough arguments in call to clipboard.Write
	have ("golang.design/x/clipboard".Format, []byte)
	want (context.Context, "golang.design/x/clipboard".Format, []byte, ..."golang.design/x/clipboard".Option)
```

Regards,
Daniel

**Comment by daniel-baumann** [comment]
I've applied the following patch in Debian to fix it:
https://forgejo.debian.net/nerdlog/nerdlog/src/branch/debian/debian/patches/debian/0001-x-clipboard.patch

**Comment by dimonomid** [comment]
Hi Daniel, thanks. Can you give me some context: is clipboard 0.9 shipped with Debian now so we need to build Nerdlog against that version as well? If so, what exactly Go version is used in Debian?

**Comment by daniel-baumann** [comment]
Hi,

in Debian we have clipboard 0.9, yes. The default Go version atm is 1.26.

Regards,
Daniel

**Comment by dimonomid** [comment]
Thanks, fixed in master in https://github.com/dimonomid/nerdlog/commit/cd353c7046a908a52efd49f9ad232aa0136b2722 .

**Comment by daniel-baumann** [comment]
great, thanks!
